package io.github.romantsisyk.nfccardreader.domain.model

data class NFCData(
    val rawResponse: String = "",
    val cardType: String? = null,
    val applicationLabel: String? = null,
    val transactionAmount: String? = null,
    val currencyCode: String? = null,
    val transactionDate: String? = null,
    val transactionStatus: String? = null,
    val applicationIdentifier: String? = null,
    val applicationTemplate: String? = null,
    val dedicatedFileName: String? = null,
    val issuerCountryCode: String? = null,
    val transactionCurrencyExponent: String? = null,
    val serviceCode: String? = null,
    val issuerUrl: String? = null,
    val paymentAccountReference: String? = null,
    val applicationCryptogram: String? = null,
    val applicationTransactionCounter: String? = null,
    val applicationInterchangeProfile: String? = null,
    val terminalVerificationResults: String? = null,
    val transactionType: String? = null,
    val issuerApplicationData: String? = null,
    val terminalCountryCode: String? = null,
    val interfaceDeviceSerialNumber: String? = null,
    val unpredictableNumber: String? = null,
    val cardholderVerificationMethodResults: String? = null,
    val issuerScriptResults: String? = null,
    val applicationCurrencyCode: String? = null,
    val transactionCategoryCode: String? = null,
    val formFactorIndicator: String? = null,
    val parsedTlvData: Map<String, String> = emptyMap()
)
